[project]
name = 'project1'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.blockpost]
path = 'contracts/blockpost.clar'
clarity_version = 2
epoch = 2.4
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
